### ISSUE TITLE
Ajuster le contenu de la table d'attributs des points

### ISSUE THREAD

**Issue by patrice-geo** [Minganie/qgis-plugin-peregrine-falcon#21]
On devrait y retrouver l'information servant à arriver au calcul du raster final. Il faudrait identifier le point le plus "probable" aussi

Exemple:

ID | Rank | Inclinaison | Proximité water | Proximité wetland

**Comment by Minganie** [comment]
Done! Rank has not been added for lack of time and also because it is easy to sort an attribute table by global score.
